name: Deploy React App to Azure Web App

on:
  push:
    branches:
      - main  # Change this if your deployment branch is different

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'  # Caches node_modules for faster builds

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "<AZURE_WEB_APP_NAME>"  # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
          package: ./build

